name: "IntroR"
project: 
  type: website
  output-dir: docs
  
website: 
  navbar:
    title: "Introduction to R"
    left:
      - text: "Home"
        href: index.html
      - text: "Set up"
        href: setup.html
      - text: "Navigating R"
        href: navigating_R.html
      - text: "Cleaning data"
        href: data_cleaning.html
      - text: "Transforming data"
        href: data_transformation.html
      - text: "Reproducibility"
        href: reproducibility.html
      - text: "Resources"
        href: resources.html
        
format: 
  html:
    theme: zephr 
    toc: true
    toc-depth: 2
    number-sections: true
