name: "IntroR"
project: 
  type: website
  output-dir: docs
  
navbar:
  title: "Introduction to R"
  left:
    - text: "Home"
      href: index.html
    - text: "Set up"
      href: setup.html
    - text: "Navigating R"
      href: navigating_R.html
    - text: "Data cleaning"
      href: data_cleaning.html
    - text: "Data wrangling"
      href: data_wrangling.html
    - text: "Reproducibility"
      href: reproducibility.html
    - text: "Resources"
      href: resources.html

output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 2
    theme: readable
    css: style.css