---
title: "Before the workshop"
---

# Workshop materials

The folder including the data and template script for the workshop can be [downloaded from github](https://github.com/emljames/introR/blob/main/workshop_files.zip). Please place this folder somewhere in your directory, and unzip the contents. Do not change any of the file structures (i.e., keep the data in the data folder, and the scripts in the script folder!). 

# Software requirements

The majority of the workshop will be "code-along" - i.e., we will be working through the material live using R, and you follow the same steps on your computer. The necessary software is already installed on the computers in the PC Lab, and you might find this option easiest given the large screens.

If you would prefer to use your own laptop, you will need to ensure you have everything set up before the workshop. We need to install both *R* itself (the programming language), and *RStudio* (an integrated software environment). Please ensure you have complete both Step 1 and Step 2 below, and reach out to Emma ([emma.james\@york.ac.uk](mailto:emma.james@york.ac.uk){.email}) if you have any difficulties.

# Step 1: Software installation

## Installation on a university-managed laptop

If you are working on a university-managed laptop, you can install R and RStudio from the Software Center (Windows) or Self Service (Mac).

## Installation on a personal device

You will need to have R and RStudio to installed to follow along with the workshop. R is the programming language itself, whereas RStudio is the user interface for interacting with R. Please make sure your software is up-to-date to avoid issues.

**To download R:**

-   Visit <https://cran.r-project.org/> and click Download R for [Windows/macOS], depending on your operating system
-   Click to install the “base” distribution, described as what you want for installing R for the first time
-   Then click to download the current version (4.5.1)
-   Once the file has downloaded, click to open it.
-   Work through the installation, sticking with all the default options
-   At some point, you might get asked to select a CRAN Mirror, which presents you with a couple of options from the UK. I’m not sure it matters which one you choose, but I always select Bristol!

**To download RStudio:**

-   Download RStudio Desktop via this link: <https://posit.co/download/rstudio-desktop/>
-   Open the file once it has downloaded, and again walk through the installer using the default options.

# Step 2: Installing relevant packages

We will use the `tidyverse` package during this workshop (don't worry - we'll cover what packages are in more detail later!). To get a head start with fixing any issues, please install it before the workshop. To do this, open up RStudio and type the following into the console (the main window that opens up, with `>` waiting for you to type).

```{r eval = FALSE}
install.packages("tidyverse")
```

Hit the return key and let it do its magic. Don't worry about the red text that flashes up - that's normal! The final messages should say that each package is *"successfully unpacked and MD5 sums checked"*. If you don't get to this point, reach out to Emma via email ([emma.james\@york.ac.uk](emma.james@york.ac.uk)).
