---
title: "Introduction to R - York Psychology ECR Workshop"
author: "Emma James"
date: "2024-10-30"
output: html_document
---

# Overview

This introductory R workshop has been put together for York Psychology ECR Forum. The workshop will take place in the PC Lab (PS/A/203), 1pm-3pm on Wednesday 6th October 2024.

The session will provide an introduction to R, providing you with the basic skills for getting started in using it in your own research. We will prioritise skills for data wrangling using a set of tools referred to as the *tidyverse*. The course is aimed at complete beginners in R -- **no programming experience or prior knowledge of R is required.**

The workshop will be led by [Emma James](https://www.york.ac.uk/psychology/staff/academicstaff/james,-emma/), with support from [Jamie Cockroft](https://www.york.ac.uk/psychology/staff/postdocs/cockcroft,-jamie/). Both Emma and Jamie have experience in using R for psychological research, and supporting beginning learners without programming backgrounds.

# Before the workshop

Before the workshop, please follow all the set-up steps on the set-up page.

# Workshop content

The main aim of this workshop is to introduce you to some key data processing tools that showcase why R can be an excellent choice for your data analysis. In doing so, we hope to given you the motivation to invest time in developing your skills in R, and confidence to do so.

This workshop consists of three key sections, with the following objectives:

1.  **Navigating R and R Studio**
    -   Why *R* and *RStudio*
    -   RStudio panes
    -   Objects
    -   Functions and packages
2.  **Data wrangling in R**
    -   Select relevant variables
    -   Rename variables
    -   Filter relevant data
    -   Calculate participant averages
    -   Create new variables
    -   Saving datasets
3.  **Reproducible research practices**
    -   The benefits of coding
    -   Always comment your code!
    -   Using Rmarkdown for readable outputs

This is quite an ambitious amount to achieve in two hours! It's hard to gauge how far we will get, but these materials are written so that you should be able to work through them independently at a later stage. You can also find some suggested resources for further learning here.

# During the workshop

### Ask for help when you need it

This is an informal setting. Emma is leading the workshop and is very not scary, so please interrupt whenever you have questions or need something explaining differently. It's very likely that she'll make mistakes and skip over things that are not obvious, so don't be afraid to ask! If you have fallen behind or something isn't working as expected, Jamie will come to your rescue!

### Sticky notes

You should have two coloured sticky notes. Please use these as instructed to indicate when you have finished an exercise, or have fallen behind and need us to slow down.

### Code of conduct

We are all learners at this workshop. Please respect that others might require a slower pace to you (you can always multi-task a little if you're ahead of the game!). We expect all instructors and attendees to be welcoming and inclusive, and respect each others' progress at all times. If you believe someone is violating this code of conduct, please let us know so that we can take the appropriate action to address the situation.
